export const GET_LAUNCHES_ACTION = 'GET_LAUNCHES';
export const RECEIVED_LAUNCHES_ACTION  = 'RECEIVED_LAUNCHES';
export const FAILED_GET_ACTION  = 'FAILED_GET_LAUNCHES';

export const ADD_LAUNCH_ACTION = 'ADD_LAUNCH';